---
- name: Installation d'Asterisk 
  hosts: asterisk_servers
  become: yes
  vars:
    asterisk_version: 22.2.0
    install_dir: /usr/src/asterisk

  tasks:
    - name: Installation des dépendances système
      apt:
        name:
          - build-essential
          - libssl-dev
          - libncurses5-dev
          - libnewt-dev
          - libxml2-dev
          - libsqlite3-dev
          - libjansson-dev
          - uuid-dev
          - libxslt1-dev
        state: present
        update_cache: yes

    - name: Création du répertoire d'installation
      file:
        path: "{{ install_dir }}"
        state: directory

    - name: Téléchargement des sources Asterisk
      get_url:
        url: https://github.com/asterisk/asterisk/archive/refs/tags/{{ asterisk_version }}.tar.gz
        dest: "/tmp/asterisk-{{ asterisk_version }}.tar.gz"

    - name: Extraction de l'archive
      unarchive:
        src: "/tmp/asterisk-{{ asterisk_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes

    - name: Configuration de la compilation
      command: ./configure
      args:
        chdir: "{{ install_dir }}/asterisk-{{ asterisk_version }}"

    - name: Compilation des modules (configuration non-interactive)
      command: make menuselect.makeopts
      args:
        chdir: "{{ install_dir }}/asterisk-{{ asterisk_version }}"

    - name: Compilation et installation
      command:
        cmd: make -j4 install
        chdir: "{{ install_dir }}/asterisk-{{ asterisk_version }}"
      become: yes

    - name: Configuration des modules essentiels
      copy:
        content: |
          [modules]
          autoload=yes
          noload => chan_sip.so
          load => chan_pjsip.so
        dest: /etc/asterisk/modules.conf
      notify: redemarrer_asterisk

    - name: Configuration PJSIP de base
      template:
        src: templates/pjsip.conf.j2
        dest: /etc/asterisk/pjsip.conf

  handlers:
    - name: redemarrer_asterisk
      systemd:
        name: asterisk
        state: restarted
        enabled: yes
