---
- name: Installation et configuration d'Asterisk
  hosts: asterisk_servers
  become: yes
  vars:
    asterisk_version: 22.2.0
    install_dir: /usr/local/src/asterisk

  tasks:
    - name: Mise à jour des paquets et installation des dépendances
      apt:
        update_cache: yes
        name:
          - build-essential
          - libssl-dev
          - libncurses5-dev
          - libnewt-dev
          - libxml2-dev
          - libsqlite3-dev
          - libjansson-dev
          - uuid-dev
        state: present

    - name: Création du répertoire d'installation
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Téléchargement des sources d'Asterisk
      get_url:
        url: "https://github.com/asterisk/asterisk/archive/refs/tags/{{ asterisk_version }}.tar.gz"
        dest: "/tmp/asterisk-{{ asterisk_version }}.tar.gz"
        mode: '0644'

    - name: Extraction de l'archive
      unarchive:
        src: "/tmp/asterisk-{{ asterisk_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes

    - name: Configuration de la compilation
      command:
        cmd: ./configure
        chdir: "{{ install_dir }}/asterisk-{{ asterisk_version }}"
      changed_when: false

    - name: Compilation et installation
      make:
        chdir: "{{ install_dir }}/asterisk-{{ asterisk_version }}"
        target: install
        params:
          -j: 4

    - name: Création du fichier de configuration des modules
      copy:
        content: |
          [modules]
          autoload=yes
        dest: /etc/asterisk/modules.conf
        owner: root
        group: root
        mode: '0644'
      notify: Redémarrer Asterisk

  handlers:
    - name: Redémarrer Asterisk
      systemd:
        name: asterisk
        state: restarted
        enabled: yes
